#!/bin/bash
JAVA_HOME=$1
logLevel=$2
if [ -z "$logLevel" ]; then
    logLevel="ERROR"
fi
NULSTAR_URL=$3
config=$4
SERVER_HOME="../../"
LIBS=$SERVER_HOME/libs
PUB_LIB=""
if [ "$5" == "address" ];
then
    MAIN_CLASS="io.nuls.cmd.client.Tools "address" $6 "
    else
    MAIN_CLASS="io.nuls.cmd.client.CmdClientBootstrap $NULSTAR_URL $6 "
fi

JAVA=${JAVA_HOME}/bin/java
for jar in `find $LIBS -name "*.jar"`
do
 PUB_LIB="$PUB_LIB:""$jar"
done
PUB_LIB="${PUB_LIB}:./cmd-client-1.0.0.jar"
# Get standard environment variables

JAVA_OPTS="-Xms128m -Xmx128m -Dapp.name=cmd-client --add-opens java.base/java.lang=ALL-UNNAMED --illegal-access=warn -Dlog.level=${logLevel} -Dactive.module=${config} "

CONF_PATH=$SERVER_HOME/conf
CLASSPATH=$CLASSPATH:$CONF_PATH:$PUB_LIB:.
if [ -x ${JAVA} ]; then
  ${JAVA} $JAVA_OPTS -classpath $CLASSPATH $MAIN_CLASS
  exit 0
fi

# $JAVA_OPTS -classpath $CLASSPATH $MAIN_CLASS

echo "The JAVA_HOME environment variable is not defined"
echo "This environment variable is needed to run this program"
exit 1