
-- CREATE TABLE IF NOT EXISTS TRANSACTION_888
-- (
--   ADDRESS VARCHAR(40) not null
--     primary key,
--   HASH    VARCHAR(70) not null,
--   TYPE    TINYINT     not null,
--   AMOUNT  BIGINT      not null,
--   STATE   TINYINT     not null,
--   TIME    BIGINT      not null
-- );
--
-- create index IF NOT EXISTS "transaction_index_888"
--   on TRANSACTION_888 (ADDRESS);